version: '2'
services:
  #mysql
  bi_db:
    image: mysql:latest
    container_name: "bi_db"
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data/sql:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/z_my.cnf

  bi_dashboard:
    image:  metabase/metabase
    container_name: "bi_dashboard"
    ports:
      - 8083:3000
    environment:
      JAVA_OPTS: "-Xmx512m -Xss512k "
      MB_DB_FILE: /metabase-data/metabase.db
    volumes:
      - ./data/metabase:/metabase-data